const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const app = $('#app'); const setup = $('#setup');
let brand = localStorage.getItem('threadline-brand') || 'Northline Studio';
let tone = 'premium'; let posterIndex = 0;
const campaigns = {
  convert:{kicker:'VIEWER → BUYER', title:'The “still thinking about it?” campaign', summary:'Make the product feel like a decision they can make today, not another tab they’ll forget.', offer:'Free shipping + a limited 48-hour “complete the fit” bundle.', hook:'“Your most-worn tee should not be your most basic one.”', channels:['EMAIL','RETARGETING','TIKTOK']},
  launch:{kicker:'DROP → DEMAND', title:'The first 100 get the story first', summary:'Turn the launch into a membership moment. Let insiders see the pieces, process, and pressure before everyone else.', offer:'48-hour early access for SMS subscribers, then a limited first-run colorway.', hook:'“You can wait for the restock, or be part of the first run.”', channels:['SMS','INSTAGRAM','EMAIL']},
  repeat:{kicker:'CUSTOMER → COLLECTOR', title:'The uniform gets better over time', summary:'Give past buyers a reason to come back that feels earned, not discounted.', offer:'A private bundle for past customers: 15% off the second piece only.', hook:'“The piece you reach for first deserves a second color.”', channels:['EMAIL','SMS','RETARGETING']},
  grow:{kicker:'SCROLL → STORE VISIT', title:'A point of view worth following', summary:'Lead with the world around the clothes so cold audiences care before you ask for the click.', offer:'No discount. Lead with the campaign, then retarget video viewers with the product.', hook:'“For people who get dressed like they have somewhere to be.”', channels:['TIKTOK','REELS','CREATOR SEEDING']}
};
const creativeDirections = [
  {title:'“The daily uniform”',desc:'Clean, tactile, unhurried. Shoot close details of the fabric, then one wide city frame. Let the texture say premium before the copy does.',tags:['LOW LIGHT','GRAIN','REAL PEOPLE'],headline:'THE UNIFORM\nFOR GOING SOMEWHERE.',color:'#bdde64'},
  {title:'“Built in the in-between”',desc:'Catch the small transition moments: elevator doors, a late train, sunlight on concrete. The product becomes the constant.',tags:['MOVEMENT','CITY','FLASH'],headline:'NOT A BASIC.\nA DEFAULT.',color:'#9eb5ff'},
  {title:'“Wear it into the ground”',desc:'Make durability feel lived-in. Show folds, texture, and repeat wear—proof that the product earns its place.',tags:['TEXTURE','ARCHIVE','HONEST'],headline:'MADE TO\nGET BETTER.',color:'#f5a16b'}
];
function applyBrand(value){ brand = value.trim() || 'Your Brand'; localStorage.setItem('threadline-brand',brand); $('#sidebar-brand').textContent=brand; $('#greeting-brand').textContent=brand.split(' ')[0]; $$('.brand-text').forEach(n=>n.textContent=brand); $('#poster-word').textContent=brand.toUpperCase(); $('#poster-tag').textContent=`${brand.toUpperCase()} / FW’26`; $('#sheet-brand').textContent=brand.toUpperCase(); $('#tee-chest').textContent=brand.split(' ')[0].toUpperCase(); document.title=`${brand} — Shopify Growth AI`; }
function enterApp(){setup.classList.add('hidden');app.classList.remove('hidden');applyBrand(brand);}
$('#brand-form').addEventListener('submit',(e)=>{e.preventDefault();applyBrand($('#brand-name').value);enterApp();});
$('#edit-brand').addEventListener('click',()=>{const next=prompt('Your clothing brand name',brand);if(next)applyBrand(next)});
$$('.nav-link').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));
$$('[data-go]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.go)));
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});}
function toast(message='Copied to clipboard'){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200);}
function copy(text, message){navigator.clipboard?.writeText(text);toast(message||'Copied to clipboard');}
$('#sync-button').addEventListener('click',()=>{const b=$('#sync-button');b.textContent='● Shopify connected';b.classList.add('primary');toast('Demo data refreshed — connect your Shopify export next');});
$('#analyze-button').addEventListener('click',()=>{const b=$('#analyze-button');b.textContent='Analyzing…';setTimeout(()=>{b.innerHTML='Analysis complete <span>✓</span>';$('#health-score').textContent='64';toast('Three new actions ranked by revenue impact');},750);});
function formatMoney(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)}
function updateCalculator(){const s=+$('#sessions-input').value,c=+$('#conversion-input').value,a=+$('#aov-input').value;const rev=s*(c/100)*a;$('#sessions-out').value=s.toLocaleString();$('#conversion-out').value=`${c.toFixed(1)}%`;$('#aov-out').value=`$${a}`;$('#projected-revenue').textContent=formatMoney(rev);$('#gap-value').textContent=rev>=10000?'Goal passed':formatMoney(10000-rev);}
['sessions-input','conversion-input','aov-input'].forEach(id=>$('#'+id).addEventListener('input',updateCalculator));updateCalculator();
$$('.choice').forEach(c=>c.addEventListener('click',()=>{$$('.choice').forEach(x=>x.classList.remove('active'));c.classList.add('active');tone=c.dataset.tone;}));
$('#generate-campaign').addEventListener('click',()=>{const plan=campaigns[$('#goal-select').value];const product=$('#product-input').value.trim()||'your hero product';$('#strategy-kicker').textContent=plan.kicker;$('#strategy-title').textContent=plan.title;$('#strategy-summary').textContent=`For ${product}, ${plan.summary.toLowerCase()}`;$('#strategy-offer').textContent=plan.offer;$('#strategy-hook').textContent=plan.hook;$('.channel-row').innerHTML=plan.channels.map(x=>`<span>${x}</span>`).join('');toast(`${tone[0].toUpperCase()+tone.slice(1)} strategy generated`);});
$('#copy-strategy').addEventListener('click',()=>copy(`${$('#strategy-title').textContent}\n\nOffer: ${$('#strategy-offer').textContent}\n\nHook: ${$('#strategy-hook').textContent}`,'Campaign copied'));
$('#copy-roadmap').addEventListener('click',()=>copy([...document.querySelectorAll('.weekly-plan li')].map(x=>x.innerText).join('\n'),'Weekly playbook copied'));
const createCreative=()=>{const d=creativeDirections[posterIndex%creativeDirections.length];const product=$('#creative-product').value||'your featured piece';$('#creative-result').innerHTML=`<strong>${d.title}</strong><p>${d.desc} Feature <b>${product.toLowerCase()}</b> as the one piece that resolves the scene.</p><div>${d.tags.map(t=>`<span>${t}</span>`).join('')}</div>`;$('#poster-copy').innerHTML=d.headline.replace('\n','<br />');$('#poster').style.setProperty('--accent',d.color);$('#poster').style.setProperty('background','#e8e0d1');$('#poster').style.setProperty('color','#1d1c19');$('#poster').setAttribute('style',`--accent:${d.color};background:#e8e0d1;color:#1d1c19`);const style=document.createElement('style');style.textContent=`.poster:before{background:${d.color}!important}`;document.head.append(style);};
$('#generate-creative').addEventListener('click',()=>{posterIndex=(posterIndex+1)%creativeDirections.length;createCreative();toast('Creative direction generated');});
$('#refresh-poster').addEventListener('click',()=>{posterIndex=(posterIndex+1)%creativeDirections.length;createCreative();});
$('#copy-shotlist').addEventListener('click',()=>copy([...document.querySelectorAll('.shot-grid article')].map(x=>x.innerText).join('\n'),'Shot list copied'));
function techData(){return {style:$('#tech-style').value,code:$('#tech-code').value,garment:$('#tech-garment').value,fit:$('#tech-fit').value,fabric:$('#tech-fabric').value,color:$('#tech-color').value,sizes:$('#tech-sizes').value,art:$('#tech-art').value};}
function generateTechpack(){const d=techData();$('#sheet-style').textContent=d.style.toUpperCase();$('#sheet-code').textContent=d.code.toUpperCase();$('#sheet-fabric').textContent=d.fabric.toUpperCase();$('#sheet-color').textContent=d.color.toUpperCase();$('#sheet-fit').textContent=d.fit.toUpperCase();$('#sheet-sizes').textContent=d.sizes.toUpperCase();$('#sheet-notes').textContent=d.art;toast('Tech pack updated');}
$('#generate-techpack').addEventListener('click',generateTechpack);
$('#add-measurement').addEventListener('click',()=>{const row=document.createElement('tr');row.innerHTML='<td contenteditable="true">New measurement</td><td contenteditable="true">Measurement method</td><td contenteditable="true">—</td><td contenteditable="true">—</td><td contenteditable="true">—</td><td contenteditable="true">—</td><td contenteditable="true">± —</td>';$('#spec-table tbody').append(row);row.querySelector('td').focus();toast('Measurement row added — click to edit');});
function techText(){const d=techData();const rows=[...document.querySelectorAll('#spec-table tbody tr')].map(row=>[...row.children].map(cell=>cell.innerText).join(' | ')).join('\n');return `${brand.toUpperCase()} — TECH PACK\nStyle: ${d.style} (${d.code})\nGarment: ${d.garment}\nFit: ${d.fit}\nFabric: ${d.fabric}\nColor: ${d.color}\nSizes: ${d.sizes}\n\nARTWORK / CONSTRUCTION NOTES\n${d.art}\n\nMEASUREMENT SPEC\n${rows}\n\nConfirm all details with the sample room before production.`;}
$('#export-techpack').addEventListener('click',()=>{generateTechpack();const blob=new Blob([techText()],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${($('#tech-code').value||'tech-pack').toLowerCase()}-tech-pack.txt`;a.click();URL.revokeObjectURL(url);toast('Production handoff exported');});
$('#print-techpack').addEventListener('click',()=>{generateTechpack();const w=window.open('','_blank');if(!w){toast('Please allow pop-ups to print the tech pack');return;}w.document.write(`<!doctype html><title>${brand} tech pack</title><style>body{font:14px Arial;padding:36px;color:#222;white-space:pre-wrap;line-height:1.55}h1{font-size:28px}</style><h1>${brand.toUpperCase()} — TECH PACK</h1><pre>${techText()}</pre>`);w.document.close();w.focus();w.print();});
if(localStorage.getItem('threadline-brand')) enterApp();
